language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
before_script:
  - cp .env
  - python manage.py migrate
script:
  - python manage.py test --settings=friendclick.settings
sudo: false