# Generated by Django 2.0.7 on 2018-07-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180730_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maxVisits',
            field=models.IntegerField(default=0),
        ),
    ]
